INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (20,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (21,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (22,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (23,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (24,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (25,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (26,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (27,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (28,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (29,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (30,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (31,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (32,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (33,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (34,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (35,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (36,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (37,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (38,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (39,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (40,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (120,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (121,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (122,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (123,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (124,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (125,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (126,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (127,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (128,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (129,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (130,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (131,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (132,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (133,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (134,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (135,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (136,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (137,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (138,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (139,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (140,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (220,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (221,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (222,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (223,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (224,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (225,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (226,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (227,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (228,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (229,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (230,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (231,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (232,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (233,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (234,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (235,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (236,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (237,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (238,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (239,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (240,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (320,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (321,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (322,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (323,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (324,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (325,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (326,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (327,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (328,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (329,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (330,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (331,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (332,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (333,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (334,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (335,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (336,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (337,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (338,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (339,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (340,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (420,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (421,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (422,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (423,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (424,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (425,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (426,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (427,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (428,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (429,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (430,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (431,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (432,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (433,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (434,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (435,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (436,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (437,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (438,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (439,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (440,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (520,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (521,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (522,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (523,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (524,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (525,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (526,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (527,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (528,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (529,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (530,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (531,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (532,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (533,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (534,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (535,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (536,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (537,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (538,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (539,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (540,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (620,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (621,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (622,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (623,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (624,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (625,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (626,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (627,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (628,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (629,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (630,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (631,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (632,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (633,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (634,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (635,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (636,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (637,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (638,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (639,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (640,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (720,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (721,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (722,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (723,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (724,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (725,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (726,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (727,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (728,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (729,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (730,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (731,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (732,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (733,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (734,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (735,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (736,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (737,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (738,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (739,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (740,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (820,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (821,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (822,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (823,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (824,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (825,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (826,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (827,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (828,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (829,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (830,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (831,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (832,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (833,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (834,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (835,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (836,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (837,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (838,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (839,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (840,TIMESTAMP('2017-02-16'),"Exceptional service","5");

INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (920,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (921,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (922,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (923,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (924,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (951,TIMESTAMP('2017-02-16'),"Highly recommended","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (926,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (927,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (928,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (929,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (930,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (931,TIMESTAMP('2017-02-16'),"Extremely resourceful tutor. Will request again!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (932,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (933,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (934,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (935,TIMESTAMP('2017-02-16'),"Exactly what I need!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (936,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (937,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (938,TIMESTAMP('2017-02-16'),"Money well spent!","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (939,TIMESTAMP('2017-02-16'),"Exceptional service","5");
INSERT INTO completedRequest (requestID,finishTime,feedback,requestRating) VALUES (940,TIMESTAMP('2017-02-16'),"Exceptional service","5");


