
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class EditServiceOffering extends javax.swing.JPanel {

    /**
     * Creates new form EditServiceOffering
     */
    public EditServiceOffering(ServiceDatabase database, Connection connect, ServiceOffering service) {
        this.database=database;
        this.connect=connect;
       //this.parent=parent;
        this.service=service;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        informLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationArea = new javax.swing.JTextArea();
        editServiceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0,204,204));
        setPreferredSize(new java.awt.Dimension(1009, 469));

        nameField.setText(service.getServiceName());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Location");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Cost(Per Hour) ");

        costField.setText(Double.toString(service.getServiceCost()));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Short Description");

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane1.setViewportView(descriptionArea);
        descriptionArea.setText(service.getDescription());

        locationArea.setColumns(20);
        locationArea.setRows(5);
        locationArea.setText(service.getLocation());
        jScrollPane2.setViewportView(locationArea);

        editServiceButton.setBackground(new java.awt.Color(32,33,55));
        editServiceButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        editServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        editServiceButton.setText("Edit");
        editServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editServiceButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        backButton.setBackground(new java.awt.Color(32,33,55));
        backButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(informLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(728, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(backButton)
                        .addGap(41, 41, 41)
                        .addComponent(editServiceButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(editServiceButton))
                .addGap(38, 38, 38)
                .addComponent(informLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editServiceButtonActionPerformed
        // NEED USER INPUT CHECKING
        int serviceID=service.getServiceID();
        String serviceName=nameField.getText();
        String serviceLocation=locationArea.getText();
        String serviceDescription=descriptionArea.getText();
        if (serviceName.equals("")) {
            JOptionPane.showMessageDialog(this, "Service Name required");
            nameField.requestFocus();
        }
        else if (serviceLocation.equals("")) {
            JOptionPane.showMessageDialog(this, "Service Location required");
            locationArea.requestFocus();
        }
        else if (costField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Service Cost required");
            costField.requestFocus();
        }
        else {
            try {
                double serviceCost = Double.parseDouble(costField.getText());
                service.setName(serviceName);
                service.setLocation(serviceLocation);
                service.setDescription(serviceDescription);
                service.setCost(serviceCost);
                statement=connect.prepareStatement("update serviceoffering set serviceName=?, serviceLocation=?, serviceDescription=?,serviceCost=? where serviceID=?");
                statement.setInt(5,serviceID);
                statement.setString(1,serviceName);
                statement.setString(2,serviceLocation);
                statement.setString(3,serviceDescription);
                statement.setDouble(4,serviceCost);
                int result=statement.executeUpdate();
                if (result!=1) {
                    //informLabel.setText("Cannot update service. Try again");
                    JOptionPane.showMessageDialog(this, "Cannot edit service");
                }
                else {
                    /*CardLayout cLayout=(CardLayout) parent.getLayout();
                    parent.removeAll();
                    parent.add(new MyOfferings(database,connect,parent),"My Offerings");
                    parent.add(new CreateServiceOffering(database,connect,parent),"Create Offering");
                    cLayout.show(parent,"My Offerings");*/

                    JTabbedPane homePane=(JTabbedPane) getParent();
                    homePane.setComponentAt(0,new MyOfferings(database,connect));
                }
            }
            catch(NumberFormatException e) {
                //informLabel.setText("Wrong format for cost");
                JOptionPane.showMessageDialog(this, "Wrong format for cost. Cannot edit service");
                costField.setText("");
                costField.requestFocus();
            }
            catch(SQLException e) {
                /*System.out.println(e);
                informLabel.setText("Cannto update service");*/
                JOptionPane.showMessageDialog(this, "Cannot edit service");
            }
        }
        
    }//GEN-LAST:event_editServiceButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        /*CardLayout cLayout=(CardLayout) parent.getLayout();
        parent.removeAll();
        parent.add(new MyOfferings(database,connect,parent),"My Offerings");
        cLayout.show(parent,"My Offerings");*/
        JTabbedPane homePane=(JTabbedPane) getParent();
        homePane.setComponentAt(0,new MyOfferings(database,connect));
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField costField;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JButton editServiceButton;
    private javax.swing.JLabel informLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea locationArea;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
    private ServiceDatabase database;
    private Connection connect;
    private PreparedStatement statement;
    private JPanel parent;
    private ServiceOffering service;
}
