
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JPanel;
import javax.swing.JTable;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage(ServiceDatabase database, Connection connect) {
        this.connect=connect;
        this.database=database;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        servicePanel = new javax.swing.JPanel();
        myRequestPanel = new javax.swing.JPanel();
        myHistoryPanel = new javax.swing.JPanel();
        logOutButton = new javax.swing.JButton();
        exitLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240,240,240));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 527));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1020, 580));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(32,33,55));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        // Code of sub-components - not shown here

        // Layout setup code - not shown here
        servicePanel = new javax.swing.JPanel();
        servicePanel.setLayout(new CardLayout());
        searchServicePanel=new SearchService(database,connect,servicePanel);
        servicePanel.add(searchServicePanel,"Search Service");
        CardLayout cLayout=(CardLayout) servicePanel.getLayout();
        cLayout.show(servicePanel,"Search Service");

        jTabbedPane1.addTab("Services", servicePanel);

        javax.swing.GroupLayout myRequestPanelLayout = new javax.swing.GroupLayout(myRequestPanel);
        myRequestPanel.setLayout(myRequestPanelLayout);
        myRequestPanelLayout.setHorizontalGroup(
            myRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        myRequestPanelLayout.setVerticalGroup(
            myRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        /*myRequestPanel.setLayout(new CardLayout());
        myRequestPanel.add(new MyRequest(database,connect,myRequestPanel),"My Requests");
        CardLayout cardLayout = (CardLayout) myRequestPanel.getLayout();
        cardLayout.show(myRequestPanel,"My Requests");*/
        myRequestPanel = new MyRequest(database,connect);

        jTabbedPane1.addTab("My Requests", myRequestPanel);

        javax.swing.GroupLayout myHistoryPanelLayout = new javax.swing.GroupLayout(myHistoryPanel);
        myHistoryPanel.setLayout(myHistoryPanelLayout);
        myHistoryPanelLayout.setHorizontalGroup(
            myHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        myHistoryPanelLayout.setVerticalGroup(
            myHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        /*myHistoryPanel.setLayout(new CardLayout());

        myHistoryPanel.add(new MyHistory(database,connect,myHistoryPanel),"My History");
        CardLayout cl=(CardLayout) myHistoryPanel.getLayout();
        cl.show(myHistoryPanel,"My History");*/
        myHistoryPanel=new MyHistory(database,connect);

        jTabbedPane1.addTab("History", myHistoryPanel);

        logOutButton.setBackground(new java.awt.Color(32,33,55));
        logOutButton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setBorderPainted(false);
        logOutButton.setOpaque(false);
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        exitLabel.setText("x");
        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 36));
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldFocusGained

    private void searchFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchFieldCaretUpdate
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchFieldCaretUpdate

    private void sortBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortBoxActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        database.setCurrentUser(null);
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    
    /*public void reloadServices() {
        servicePanel.removeAll();
        servicePanel.add(new SearchService(database,connect,servicePanel),"Search Service");
    }*/
    
    public SearchService getSearchServicePanel() {
        return searchServicePanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel myHistoryPanel;
    private javax.swing.JPanel myRequestPanel;
    private javax.swing.JPanel servicePanel;
    // End of variables declaration//GEN-END:variables
    private ServiceDatabase database;
    private Connection connect;
    private PreparedStatement statement;
    private SearchService searchServicePanel;
}
