/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
import java.awt.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        platformPanel.setBackground(new Color(0,0,0,170));
        database=new ServiceDatabase();
        try {
            connect = DriverManager.getConnection("jdbc:mysql://localhost/servicesharing?autoReconnect=true&useSSL=false","admin","adminpw"); //set up connection with DB
            preparedStatement = connect.prepareStatement("select * from user");
            resultSet=preparedStatement.executeQuery();
            database.loadUsers(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from user join provider on user.username=provider.username");
            resultSet=preparedStatement.executeQuery();
            database.loadProviders(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from serviceOffering");
            resultSet=preparedStatement.executeQuery();
            database.loadServiceOfferings(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from serviceRequest");
            resultSet=preparedStatement.executeQuery();
            database.loadRequests(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from completedRequest join serviceRequest on completedRequest.requestID=serviceRequest.requestID");
            resultSet=preparedStatement.executeQuery();
            database.loadCompletedRequests(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from transaction");
            resultSet=preparedStatement.executeQuery();
            database.loadTransactions(resultSet);
            
            preparedStatement=connect.prepareStatement("select * from card");
            resultSet=preparedStatement.executeQuery();
            database.loadCards(resultSet);
        }
        catch(SQLException e) {
            System.out.println(e);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        platformPanel = new javax.swing.JPanel();
        sloganField = new javax.swing.JLabel();
        platformNameField = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        informLabel = new javax.swing.JLabel();
        createLabel = new javax.swing.JLabel();
        providerLoginLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 527));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        platformPanel.setBackground(new java.awt.Color(0, 0, 0));

        sloganField.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        sloganField.setForeground(new java.awt.Color(255, 255, 255));
        sloganField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sloganField.setText("For a better future");

        platformNameField.setFont(new java.awt.Font("Poor Richard", 0, 48)); // NOI18N
        platformNameField.setForeground(new java.awt.Color(255, 255, 255));
        platformNameField.setText("Gateway Tutoring");

        javax.swing.GroupLayout platformPanelLayout = new javax.swing.GroupLayout(platformPanel);
        platformPanel.setLayout(platformPanelLayout);
        platformPanelLayout.setHorizontalGroup(
            platformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platformPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(platformNameField)
                .addGap(82, 82, 82))
            .addGroup(platformPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(sloganField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        platformPanelLayout.setVerticalGroup(
            platformPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platformPanelLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(platformNameField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sloganField)
                .addGap(265, 265, 265))
        );

        getContentPane().add(platformPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 560));

        loginPanel.setBackground(new java.awt.Color(32, 33, 35));

        usernameField.setBackground(new java.awt.Color(32, 33, 35));
        usernameField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        usernameField.setBorder(null);
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        jSeparator1.setFocusable(true);
        jSeparator1.setName(""); // NOI18N

        passwordField.setBackground(new java.awt.Color(32, 33, 35));
        passwordField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        passwordField.setBorder(null);
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(153, 153, 153));
        nameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 153, 153));
        passwordLabel.setText("Password");

        loginLabel.setBackground(new java.awt.Color(102, 102, 102));
        loginLabel.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login as User");
        loginLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginLabel.setOpaque(true);
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });

        informLabel.setForeground(new java.awt.Color(204, 204, 204));
        informLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        createLabel.setBackground(new java.awt.Color(255, 255, 255));
        createLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        createLabel.setForeground(new java.awt.Color(255, 255, 255));
        createLabel.setText("Don't have an account? Register");
        createLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createLabelMouseClicked(evt);
            }
        });

        providerLoginLabel.setBackground(new java.awt.Color(102, 102, 102));
        providerLoginLabel.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        providerLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        providerLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        providerLoginLabel.setText("Login as Provider");
        providerLoginLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        providerLoginLabel.setOpaque(true);
        providerLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providerLoginLabelMouseClicked(evt);
            }
        });

        exitLabel.setText("x");
        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 36));
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(createLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(informLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(providerLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jSeparator3))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        informLabel.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N

        informLabel.setForeground(new java.awt.Color(153, 153, 153));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 520, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        jSeparator1.setBackground(new Color (57,113,177));
        nameLabel.setForeground(new Color (57,113,177));
    }//GEN-LAST:event_usernameFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        jSeparator3.setBackground(new Color (57,113,177));
        passwordLabel.setForeground(new Color (57,113,177));
    }//GEN-LAST:event_passwordFieldFocusGained

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        nameLabel.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_usernameFieldFocusLost

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        passwordLabel.setForeground(new Color (153,153,153));
    }//GEN-LAST:event_passwordFieldFocusLost

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        // LOGIN Function
        String username= usernameField.getText();
        String password= new String(passwordField.getPassword());
        if (database.checkUser(username,password)) {
            database.setCurrentUser(database.getUser(username));
            Homepage homepage= new Homepage(database,connect);
            dispose();
            homepage.setVisible(true);
        }
        else {
            informLabel.setText("Wrong username or password");
            usernameField.setText("");
            passwordField.setText("");
            usernameField.requestFocus();
        }
    }//GEN-LAST:event_loginLabelMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
        String username= usernameField.getText();
        String password= new String(passwordField.getPassword());
        if (database.checkUser(username,password)) {
            database.setCurrentUser(database.getUser(username));
            Homepage homepage= new Homepage(database,connect);
            dispose();
            homepage.setVisible(true);
        }
        else {
            informLabel.setText("Wrong username or password");
            usernameField.setText("");
            passwordField.setText("");
            usernameField.requestFocus();
        }
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void createLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseClicked
        // TODO add your handling code here:
        CreateAccount createAccount=new CreateAccount(database,connect);
        dispose();
        createAccount.setVisible(true);
    }//GEN-LAST:event_createLabelMouseClicked

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void providerLoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providerLoginLabelMouseClicked
        // TODO add your handling code here:
        String username= usernameField.getText();
        String password= new String(passwordField.getPassword());
        if (database.checkProvider(username, password)) {
            database.setCurrentUser(database.getUser(username));
            //System.out.println(database.getCurrentUser().getUsername());
            ProviderHomePage providerHomepage = new ProviderHomePage(database,connect);
            dispose();
            providerHomepage.setVisible(true);
        }
        else {
            informLabel.setText("Wrong username or password");
            usernameField.setText("");
            passwordField.setText("");
            usernameField.requestFocus();
        }
    }//GEN-LAST:event_providerLoginLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run() {
                Login login = new Login();
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel informLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel platformNameField;
    private javax.swing.JPanel platformPanel;
    private javax.swing.JLabel providerLoginLabel;
    private javax.swing.JLabel sloganField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
    private Connection connect = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet=null;
    private ServiceDatabase database=null;
}

